name: Makefile CI
permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make
      run: make old-reddit-redirect-v2.0.5-esr.xpi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: v2.0.5-esr
        tag_name: v2.0.5-esr
        files: old-reddit-redirect-v2.0.5-esr.xpi
